esphome:
  name: ${name}
  comment: Everything Presence Lite
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True
  project: 
    name: EverythingSmartTechnology.Everything Presence Lite
    version: "1.2.2"

esp32:
  board: ${board}
  framework:
    type: esp-idf

# Enable logging
logger:
  level: ${log_level} 

http_request:

improv_serial:

i2c:
-  id: bus_a
   sda: 21
   scl: 22
   scan: true