esphome:
  name: ${name}
  comment: Everything Presence Lite
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True
  project: 
    name: EverythingSmartTechnology.Everything Presence Lite
    version: "1.2.2"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_presence_flur

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

http_request:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: !secret static_ip_presence_flur

improv_seriasl:

i2c:
-  id: bus_a
   sda: 21
   scl: 22
   scan: true