esphome:
  on_boot:
    then:
      - switch.turn_on: engineering_mode

uart:
  id: uart_bus
  baud_rate:  256000
  rx_pin: ${rx_pin}
  tx_pin: ${tx_pin}
  parity: NONE
  stop_bits: 1

ld2410:

globals:
  - id: occupancy_delay
    type: int
    initial_value: "500"

binary_sensor:
  - platform: ld2410
    has_target:
      name: Occupancy
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
  - platform: gpio
    pin: 18
    name: Occupancy
    device_class: Occupancy

  - platform: template
    name: "Occupancy Actual"
    lambda: |-
      static unsigned long last_trigger_time = 0;  // Stores the last time the sensor triggered
      unsigned long current_time = millis();  // Get the current time

      // Check if any energy values exceed the threshold
      bool motion_detected = (
        id(gate_0_still_energy).state > id(gate_0_still_threshold).state ||
        id(gate_1_still_energy).state > id(gate_1_still_threshold).state ||
        id(gate_2_still_energy).state > id(gate_2_still_threshold).state ||
        id(gate_3_still_energy).state > id(gate_3_still_threshold).state ||
        id(gate_4_still_energy).state > id(gate_4_still_threshold).state ||
        id(gate_5_still_energy).state > id(gate_5_still_threshold).state ||
        id(gate_6_still_energy).state > id(gate_6_still_threshold).state ||
        id(gate_7_still_energy).state > id(gate_7_still_threshold).state ||
        id(gate_8_still_energy).state > id(gate_8_still_threshold).state ||
        id(gate_0_movement_energy).state > id(gate_0_movement_threshold).state ||
        id(gate_1_movement_energy).state > id(gate_1_movement_threshold).state ||
        id(gate_2_movement_energy).state > id(gate_2_movement_threshold).state ||
        id(gate_3_movement_energy).state > id(gate_3_movement_threshold).state ||
        id(gate_4_movement_energy).state > id(gate_4_movement_threshold).state ||
        id(gate_5_movement_energy).state > id(gate_5_movement_threshold).state ||
        id(gate_6_movement_energy).state > id(gate_6_movement_threshold).state ||
        id(gate_7_movement_energy).state > id(gate_7_movement_threshold).state ||
        id(gate_8_movement_energy).state > id(gate_8_movement_threshold).state
      );

      // Trigger only if motion is detected and 1 second has passed since the last trigger
      if (motion_detected && (current_time - last_trigger_time > id(=occupancy_delay))) {
        last_trigger_time = current_time;  // Update last trigger time
        return true;  // Trigger motion
      }
      return false;  // No trigger
    device_class: motion

sensor:
  - platform: ld2410
    light:
      name: mmWave Light
      disabled_by_default: true
    moving_distance:
      name: Moving Target Distance
    still_distance:
      name: Still Target Distance
    moving_energy:
      name: Moveing Target Energy
    still_energy:
      name: Still Target Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: Gate 0 Movement Energy
        id: gate_0_movement_energy
      still_energy:
        name: Gate 0 Still Energy
        id: gate_0_still_energy
    g1:
      move_energy:
        name: Gate 1 Movement Energy
        id: gate_1_movement_energy
      still_energy:
        name: Gate 1 Still Energy
        id: gate_1_still_energy
    g2:
      move_energy:
        name: Gate 2 Movement Energy
        id: gate_2_movement_energy
      still_energy:
        name: Gate 2 Still Energy
        id: gate_2_still_energy
    g3:
      move_energy:
        name: Gate 3 Movement Energy
        id: gate_3_movement_energy
      still_energy:
        name: Gate 3 Still Energy
        id: gate_3_still_energy
    g4:
      move_energy:
        name: Gate 4 Movement Energy
        id: gate_4_movement_energy
      still_energy:
        name: Gate 4 Still Energy
        id: gate_4_still_energy
    g5:
      move_energy:
        name: Gate 5 Movement Energy
        id: gate_5_movement_energy
      still_energy:
        name: Gate 5 Still Energy
        id: gate_5_still_energy
    g6:
      move_energy:
        name: Gate 6 Movement Energy
        id: gate_6_movement_energy
      still_energy:
        name: Gate 6 Still Energy
        id: gate_6_still_energy
    g7:
      move_energy:
        name: Gate 7 Movement Energy
        id: gate_7_movement_energy
      still_energy:
        name: Gate 7 Still Energy
        id: gate_7_still_energy
    g8:
      move_energy:
        name: Gate 8 Movement Energy
        id: gate_8_movement_energy
      still_energy:
        name: Gate 8 Still Energy
        id: gate_8_still_energy

switch:
  - platform: ld2410
    engineering_mode:
      name: "Engineering Mode"
      id: "engineering_mode"
    bluetooth:
      name: "mmWave Bluetooth"
      disabled_by_default: true

number:
  - platform: template
    name: "Occupancy Delay"
    id: "occupany_delay_input"
    optimistic: true
    min_value: 0
    max_value: 5000
    step: 1
    on_value:
      then:
        - lambda: |-
            id(occupancy_delay) = x;

  - platform: ld2410
    timeout:
      name: Occupancy Off Delay
    light_threshold:
      name: mmWave Light Threshold
      disabled_by_default: True
    max_move_distance_gate:
      name: Max Movement Distance Gate
    max_still_distance_gate:
      name: Max Still Distance Gate
    g0:
      move_threshold:
        name: Gate 0 Movement Sensitivity
        id: gate_0_movement_threshold
      still_threshold:
        name: Gate 0 Still Sensitivity
        id: gate_0_still_threshold
    g1:
      move_threshold:
        name: Gate 1 Movement Sensitivity
        id: gate_1_movement_threshold
      still_threshold:
        name: Gate 1 Still Sensitivity
        id: gate_1_still_threshold
    g2:
      move_threshold:
        name: Gate 2 Movement Sensitivity
        id: gate_2_movement_threshold
      still_threshold:
        name: Gate 2 Still Sensitivity
        id: gate_2_still_threshold
    g3:
      move_threshold:
        name: Gate 3 Movement Sensitivity
        id: gate_3_movement_threshold
      still_threshold:
        name: Gate 3 Still Sensitivity
        id: gate_3_still_threshold
    g4:
      move_threshold:
        name: Gate 4 Movement Sensitivity
        id: gate_4_movement_threshold
      still_threshold:
        name: Gate 4 Still Sensitivity
        id: gate_4_still_threshold
    g5:
      move_threshold:
        name: Gate 5 Movement Sensitivity
        id: gate_5_movement_threshold
      still_threshold:
        name: Gate 5 Still Sensitivity
        id: gate_5_still_threshold
    g6:
      move_threshold:
        name: Gate 6 Movement Sensitivity
        id: gate_6_movement_threshold
      still_threshold:
        name: Gate 6 Still Sensitivity
        id: gate_6_still_threshold
    g7:
      move_threshold:
        name: Gate 7 Movement Sensitivity
        id: gate_7_movement_threshold
      still_threshold:
        name: Gate 7 Still Sensitivity
        id: gate_7_still_threshold
    g8:
      move_threshold:
        name: Gate 8 Movement Sensitivity
        id: gate_8_movement_threshold
      still_threshold:
        name: Gate 8 Still Sensitivity
        id: gate_8_still_threshold

button:
  - platform: ld2410
    factory_reset:
      name: "Factory Reset mmWave"
      disabled_by_default: true
    restart:
      name: "Restart mmWave"
      disabled_by_default: true
    query_params:
      name: Get Values
      disabled_by_default: true

text_sensor:
  - platform: ld2410
    version:
      name: "mmWave Firmware Version"
    mac_address:
      name: "mmWave MAC Address"
      disabled_by_default: true

select:
  - platform: ld2410
    distance_resolution:
      name: "Distance Gate Resolution"
      disabled_by_default: true
    baud_rate:
      name: "mmWave Sensor Baud Rate"
      disabled_by_default: true
    light_function:
      name: mmWave Light Function
      disabled_by_default: true
    out_pin_level:
      name: GPIO Pin Level
      disabled_by_default: true
